# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '水印笔记' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 水印笔记
    pod 'MBProgressHUD',:inhibit_warnings => true
    pod 'MJRefresh',:inhibit_warnings => true
    pod 'SDWebImage',:inhibit_warnings => true
    pod 'AFNetworking',:inhibit_warnings => true
    pod 'FMDB',:inhibit_warnings => true
    pod 'MJExtension',:inhibit_warnings => true
    pod 'SDAutoLayout',:inhibit_warnings => true
    pod 'YYKit',:inhibit_warnings => true
    pod 'SAMKeychain',:inhibit_warnings => true
    pod 'TZImagePickerController'
    pod 'Qiniu'
    pod 'JPush'

end
